### PR TITLE
Gradle Sample

### PR DESCRIPTION
**Pull request by darylteo**

### CODE REVIEW

**Comment by stephanenicolas** [comment]
Lol, yes you could ;)

**Comment by stephanenicolas** [comment]
There are some things I don't catch in the sample : 
- which processor is used by transform2 ? 
- where does the script import classes from ?
- how to copy the transformed classes into the normal build dir output after success ?

**Comment by darylteo** [comment]
Hi Stephane,

   the transformer class is in /buildSrc. This is one of the ways Gradle
allows you to write classes that are imported into the buildscript.

Alternatively, the class can be written directly into the script.
3rdly, the class can be in a standalone project hosted on a repository and
imported in via dependencies.

As for how to copy the transformed classes, it depends on what you intend
to do with it. If you want to add it in as a Jar, you simply tell the Jar
task (or create a new artifact) to include the output of those
transformations. Its a standard Gradle procedure.

Daryl

**Comment by darylteo** [comment]
``` bash
Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: javassist.CannotCompileException: [source error] ; is missing
    at com.darylteo.gradle.javassist.transformers.GroovyClassTransformation.applyTransformations(GroovyClassTransformation.java:25)
    at com.darylteo.gradle.javassist.tasks.TransformationAction$LoaderAction.processFile(TransformationAction.java:86)
    ... 100 more
Caused by: javassist.CannotCompileException: [source error] ; is missing
    at javassist.CtNewMethod.make(CtNewMethod.java:79)
    at javassist.CtNewMethod.make(CtNewMethod.java:45)
    at com.github.stephanenicolas.afterburner.AfterBurner.addOrInsertMethod(AfterBurner.java:54)
    at com.github.stephanenicolas.afterburner.InsertableMethodBuilder$StateComplete.doIt(InsertableMethodBuilder.java:175)
    at com.github.stephanenicolas.afterburner.InsertableMethodBuilder$StateComplete$doIt.call(Unknown Source)
    at build_583ghtgffthha8d9v5vvqqjbf7$_run_closure1_closure5.doCall(/Users/dteo/workspaces/sandbox/afterburner/afterburner-gradle-sample/build.gradle:37)
    ... 102 more
Caused by: compile error: ; is missing
    at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:594)
    at javassist.compiler.Parser.parseStatement(Parser.java:277)
    at javassist.compiler.Parser.parseBlock(Parser.java:289)
    at javassist.compiler.Parser.parseMethod2(Parser.java:152)
    at javassist.compiler.Javac.compileMethod(Javac.java:149)
    at javassist.compiler.Javac.compile(Javac.java:95)
    at javassist.CtNewMethod.make(CtNewMethod.java:74)
    ... 107 more
```

**Comment by darylteo** [comment]
Added some Jar sample. If you think this makes sense, I will submit another PR. Once the above is fixed and I test the results are as expected.

https://github.com/darylteo/afterburner/blob/sample/afterburner-gradle-sample/build.gradle

**Pull request merged**
